/*
 * Generated by xView
 *
 *   :-)    :-)    :-)    :-)    :-)    :-)
 *  /   \  /   \  /   \  /   \  /   \  /   \
 * | ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ |
 *  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/
 *
 */

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'simple_view_model.dart';


class SimplePage extends StatefulWidget {
  final String title;

  const SimplePage({super.key, this.title = 'SimplePage'});

  @override
  State<SimplePage> createState() => _SimplePageState();
}

class _SimplePageState extends State<SimplePage> {
  @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider(
      create: (_) => SimpleViewModel(),
      builder: (childContext, child) {
        return _builder(childContext);
      },
    );
  }

  Widget _builder(BuildContext childContext) {
    return Scaffold(
      appBar: AppBar(title: Text(widget.title)),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildCounter(),
            const SizedBox(height: 40),
            ElevatedButton(
              onPressed: () => childContext.read<SimpleViewModel>().incrementA(),
              child: const Text('+'),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCounter() {
    return Selector<SimpleViewModel, int>(
      selector: (_, vm) => vm.count,
      builder: (context, val, _) => Text('$val'),
    );
  }
}
