/*
 * Generated by xView
 *
 *   :-)    :-)    :-)    :-)    :-)    :-)
 *  /   \  /   \  /   \  /   \  /   \  /   \
 * | ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ |
 *  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/
 *
 */

import 'package:flutter/cupertino.dart';

class SimpleViewModel extends ChangeNotifier {
  int _count = 0;

  int get count => _count;

  void incrementA() {
    _count++;
    notifyListeners();
  }

  @override
  void dispose() {
    super.dispose();
  }
}
