import 'example_view_model.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import '../../widgets/custom_appbar.dart';
import '../../../core/extension/image_extensions.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/extension/asyncvalue_extensions.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

/*
 * Generated by xView
 *
 *   :-)    :-)    :-)    :-)    :-)    :-)
 *  /   \  /   \  /   \  /   \  /   \  /   \
 * | ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ |
 *  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/
 *
 *   command: dart run build_runner watch
 */

class ExamplePage extends ConsumerStatefulWidget {
  final String title;
  final String pageId;

  const ExamplePage({super.key, required this.pageId, this.title = 'example-page'});

  @override
  ConsumerState<ExamplePage> createState() => _ExamplePageState();
}

class _ExamplePageState extends ConsumerState<ExamplePage> {
  ExampleViewModelProvider get _exampleViewModelProvider => exampleViewModelProvider(widget.title);

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {
      //todo something
    });
  }

  @override
  Widget build(BuildContext context) {
    final ExampleViewModel viewModel = ref.read(_exampleViewModelProvider.notifier);
    return Scaffold(
      appBar: _buildAppbar(),
      body: _buildBody(),
      floatingActionButton: _buildFloatingAction(context, viewModel),
    );
  }

  PreferredSizeWidget _buildAppbar() {
    return const CustomAppBar(title: 'exampleArm-page', showBackButton: false);
  }

  Widget _buildBody() {
    return Column(
      children: [
        _buildCount(),
        const SizedBox(height: 40),
        _buildBanner(),
      ],
    );
  }

  Widget _buildCount() {
    return Consumer(builder: (context, ref, _) {
      int count = ref.watch(_exampleViewModelProvider.select((state) => state.count));
      return Text(
        'Count: $count',
        style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
      );
    });
  }

  Widget _buildBanner() {
    return Consumer(builder: (context, ref, _) {
      return ref.watch(_exampleViewModelProvider.select((state) => state.bannerAsyncValue)).buildWhen(
        data: (bannerEntity) {
          return Container(
            width: double.infinity,
            height: 150.h,
            child: ImageLoader.network(src: bannerEntity?.data[0].imagePath),
          );
        },
      );
    });
  }

  Widget _buildFloatingAction(BuildContext context, ExampleViewModel viewModel) {
    return FloatingActionButton(
      onPressed: () {
        viewModel.increment();
      },
      child: const Icon(Icons.add),
    );
  }
}
