import 'example_state.dart';
import 'example_view_model.dart';
import 'package:flutter/material.dart';
import '../../../src/widgets/custom_appbar.dart';
import '../../../core/extension/image_extensions.dart';
import '../../../core/extension/widget_extensions.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../../core/extension/asyncvalue_extensions.dart';

/*
 * Generated by xView
 *
 *   :-)    :-)    :-)    :-)    :-)    :-)
 *  /   \  /   \  /   \  /   \  /   \  /   \
 * | ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ || ^ ^ |
 *  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/  \_v_/
 *
 *   command: dart run build_runner watch
 */

class ExamplePage extends ConsumerWidget {
  final String title;
  final String pageId;

  const ExamplePage({super.key, required this.pageId, this.title = 'example-page'});

  PreferredSizeWidget _buildAppbar() {
    return const CustomAppBar(title: 'example-page', showBackButton: false);
  }

  Widget _buildBody(ExampleState state, ExampleViewModel viewModel) {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text(
            'Count: ${state.count}',
            style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
          ),
          const SizedBox(height: 16),
          state.bannerAsyncValue.buildWhen(data: (bannerEntity) {
            return SizedBox(
              width: double.infinity,
              height: 150,
              child: ImageLoader.network(src: bannerEntity?.data[0].imagePath ?? ''),
            ).withSkeletonizer(bannerEntity == null);
          }),
        ],
      ),
    );
  }

  Widget _buildFloatingAction(ExampleViewModel viewModel) {
    return FloatingActionButton(
      onPressed: () {
        viewModel.increment();
      },
      child: const Icon(Icons.add),
    );
  }

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final ExampleState state = ref.watch(exampleViewModelProvider(pageId));
    final ExampleViewModel viewModel = ref.read(exampleViewModelProvider(pageId).notifier);
    return Scaffold(
      appBar: _buildAppbar(),
      body: _buildBody(state, viewModel),
      floatingActionButton: _buildFloatingAction(viewModel),
    );
  }
}
